### ISSUE TITLE
Spelling Mistake in Heading

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/CreditCardVerifier#1]
**Describe the bug**
The word "Checker" is misspelled as "Chcker" in index.html

**To Reproduce**
1. Open index.html
2. Go to the h1 tag

**Expected behavior**
Should be spelled correct

**Comment by abhishek-pes** [comment]
hey @srujandeshpande  i would like to work on this

**Comment by kkumuda** [comment]
hey, can i do this?
