### ISSUE TITLE
[ENHANCEMENT] Show Issuing Bank/Service of Credit Card (i.e. Visa, Mastercard, etc)

### ISSUE THREAD

**Issue by anirudhRowjee** [acmpesuecc/CreditCardVerifier#13]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but an enhancement. This would be a useful real-life application.

**Describe the solution you'd like**
The application should tell you if the card is issued by Mastercard, Visa, or American Express. I'd like to implement regex-based validation for each of these, as per these rules - 

>Actually, that’s a bit of an exaggeration, because credit card numbers actually have some structure to them. All American Express numbers start with 34 or 37; most MasterCard numbers start with 51, 52, 53, 54, or 55 (they also have some other potential starting numbers which we won’t concern ourselves with for this problem); and all Visa numbers start with 4.

_taken from [CS50x](https://cs50.harvard.edu/college/2020/fall/psets/1/credit/)_

**Describe alternatives you've considered**
One could make a request to the various BIN/IIN APIs (for example, [this one](https://binlist.net/))

**Additional context**
no addtional context.

**Comment by anirudhRowjee** [comment]
If this is accepted, I would like to work on this.

**Comment by srujandeshpande** [comment]
!bounty 5 (Brownie points for bringiing up a great suggestion!)

**Comment by anirudhRowjee** [comment]
Thank you :smile:
