### ISSUE TITLE
Update User Interface.

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/CreditCardVerifier#19]
The user interface is garbage. It is upto your discretion to make it look better.

Some suggestions: (Not binding)
1. Change background
2. Incorporate a library similar to Bootstrap to make the User interface look better
3. Anything else that could make it look good

The bounty points you recieve will depend on the extent of imporvments you make!

**Comment by sreechand2002** [comment]
i would like to work on it

**Comment by ShreyaPanale** [comment]
Hey, I would like to work on this as well
