### ISSUE TITLE
Make the input field only accept numbers

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/CreditCardVerifier#3]
**Describe the bug**
Currently, the input field accepts text, special characters and numbers

**Expected behavior**
Only number should be allowed to be entered

**Additional context**
Changing the input type might help

**Comment by honsq90** [comment]
I can take this

**Comment by arnxv0** [comment]
Can I work on this?

**Comment by Devprakash613** [comment]
Can I work on this?
