### ISSUE TITLE
Missing <head> Closing tag

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/CreditCardVerifier#34]
The </head> tag is incorrectly written as <head>

**Comment by kittu2karthik** [comment]
hey @srujandeshpande can you assign this to me

**Comment by tremby** [comment]
Looks like this was fixed in #38.

**Comment by Sunairaa** [comment]
Hey @srujandeshpande can i work on this issue?

**Comment by tremby** [comment]
It was already fixed when #38 was merged but for some reason hasn't been closed.

**Comment by srujandeshpande** [comment]
@tremby This issue was one of many created to promote first time open source contributions and hence we accepted multiple PRs for the same Issue
