### ISSUE TITLE
Add more types of Cards to the "Type" field

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/CreditCardVerifier#44]
**Is your feature request related to a problem? Please describe.**
Currently, only Mastercard, Visa and AMEX card types are returned by the code when verifying the number

**Describe the solution you'd like**
Add support for more card types (Ex: Discover, JCB, etc)

**Comment by JorgeMadson** [comment]
I will put more cards in this pull request.

**Comment by NavinShrinivas** [comment]
Sure go ahead , but we already have a valid pr and has been accepted , we assign bounties only to prs that came in first

**Comment by saisudhirs** [comment]
I found few optimizations that can be to card numbers formats .Also, I'm adding a few major cards that have been missing, so please assign the issue such that I can improvise it.

**Comment by anirudhRowjee** [comment]
Hi, @saisudhirs!
Please open an issue with this point, so we can discuss further.

**Comment by saisudhirs** [comment]
@anirudhRowjee Sir I have opened a new issue, please create tags for it and also assign me to it
Thank you

**Comment by JoyenBenitto** [comment]
I would like to work on this
