### ISSUE TITLE
Loading insecure content on a secure page

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/CreditCardVerifier#46]
After visiting the deployed page in `https://acmpesuecc.github.io/CreditCardVerifier`, the console gives us the error message `Loading mixed (insecure) display content “http://africalegalnetwork.com/nigeria/wp-content/uploads/sites/19/2017/08/Banking.jpg” on a secure page`

This is due to the background image coming from an insecure (http) website while ours is hosted on the more secure https.

To fix this, head to unsplash.com or any similar site and find a royalty free image for the background. Provide a link to that image instead making sure that it has the https prefix

**Comment by V3dant** [comment]
@srujandeshpande please have a look into this issue.
