### ISSUE TITLE
Add a margin at the bottom of the page

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/CreditCardVerifier#51]
When scrolling to the bottom of the page, there is no margin between the end of the black box and the end of the page. It would be nice to have one matching the margin at the top of the page

**Comment by V3dant** [comment]
This issue is fixed in #53. Have a look into it.

**Comment by staysee** [comment]
can i get assigned to this?

**Comment by staysee** [comment]
Hi I'm not sure if I submitted my PR correctly? Can you let me know?

**Comment by srujandeshpande** [comment]
@staysee Your PR was perfect, thanks!
