### ISSUE TITLE
Form does not submit on pressing enter key

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/CreditCardVerifier#57]
### What happened?

When a credit card number is entered into the textbox, pressing enter does not submit the form. Instead, it refreshes the page. Ideally, it should work such that pressing the enter key submits the form and displays the result.

### What device are you seeing the problem on?

Desktop

### What browsers are you seeing the problem on?

Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manasa-sm** [comment]
heyy i wanna try this
